openapi: 3.0.0


info:
  title: GeekMeet backend
  description: ""
  version: 0.0.1


servers:
  - url: /api/v2

tags:
  - name: "user"
    description: "Действия с пользователем"
    
  - name: feed
    description: "Действия с лентой"
    
  - name: event
    description: "Действия с ивентами"
    
  - name: tag
    description: "Действия с тэгами"


paths:
  /user/register:
    post:
      summary: Создание пользователя и авторизация
      tags:
        - "user"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                login:
                  type: string
                password:
                  type: string
                email:
                  type: string
                about:
                  type: string
                avatar:
                  type: string
                tags:
                  type: array
                  items:
                    type: integer
              required:
                - login
                - password
                - email
                - tags
                - avatar
      responses:
        '200':    # status code
          description: Токен авторизации, если регистрация прошла успешно
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
        '400':    # status code
          description: Произошла ошибка
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string

  /user/login:
    post:
      summary: Авторизация
      tags:
        - "user"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                login:
                  type: string
                password:
                  type: string
              required:
                - login
                - password
      responses:
        '200':    # status code
          description: Токен авторизации
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
        '400':    # status code
          description: Произошла ошибка
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string

  /user/{id}:
    get:
      summary: Получение пользователя по id
      tags:
        - "user"
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
        - name: Authorization
          in: header
          required: true
          schema:
            type: string
      responses:
        '200':    # status code
          description: Данные пользователя по его id
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  login:
                    type: string
                  about:
                    type: string
                  avatar:
                    type: string
                  tags:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: integer
                        title:
                          type: string
                  request:
                    type: object
                    properties:
                      status:
                        type: string
                      target:
                        type: integer

  /user/:
    patch:
      summary: Изменение информации пользователя о себе
      tags:
        - "user"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                login:
                  type: string
                password:
                  type: string
                email:
                  type: string
                about:
                  type: string
                avatar:
                  type: string
                tags:
                  type: array
                  items:
                    type: integer
      responses:
        '200':    # status code
          description: Изменение прошло успешно
        '400':    # status code
          description: Произошла ошибка
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string



  /feed/:
    get:
      summary: Получение ленты ивентов
      tags:
        - feed
      responses:
        '200':    # status code
          description: Список всех предстоящих ивентов
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                    name:
                      type: string
                    date:
                      type: string
                    address:
                      type: string
                    photo:
                      type: string
                    seats:
                      type: integer
                    tags:
                      type: array
                      items:
                        type: object
                        properties:
                          id:
                            type: integer
                          title:
                            type: string
                    isFavorite:
                      type: boolean
                    request:
                      type: object
                      properties:
                        status:
                          type: string

  /feed/new:
    get:
      summary: Получение новых ивентов (свайпер)
      tags:
        - feed
      responses:
        '200':    # status code
          description: Список всех новых ивентов
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                    name:
                      type: string
                    date:
                      type: string
                    photo:
                      type: string
                    address:
                      type: object
                      properties:
                        name:
                          type: string
                        address:
                          type: string
                        metro:
                          type: string

  /event/create:
    post:
      summary: Создание нового ивента
      tags:
        - event
      parameters:
        - name: Authorization
          in: header
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                date:
                  type: string
                seats:
                  type: integer
                address:
                  type: object
                  properties:
                    name:
                      type: string
                    address:
                      type: string
                    metro:
                      type: string
                tags:
                  type: array
                  items:
                    type: object
                    properties:
                      id:
                        type: integer
                      title:
                        type: string
                about:
                  type: string
                photo:
                  type: string
      responses:
        '200':    # status code
          description: Ивент создан
        '400':    # status code
          description: Произошла ошибка
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string

  /tag/:
    get:
      summary: Получение всех тэгов
      tags:
        - tag
      responses:
        '200':    # status code
          description: Список всех тэгов
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                    title:
                      type: string
    post:
      summary: Создание нового тэга
      tags:
        - tag
      parameters:
        - name: Authorization
          in: header
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
              required:
                - title
      responses:
        '200':    # status code
          description: Тэг создан
        '400':    # status code
          description: Произошла ошибка
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
  